# 05 numpy.array 的基本操作

In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size

10

In [10]:
X.size

15

### numpy.array 的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0]

0

In [16]:
X[2,2]

12

In [17]:
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
x[:5]

array([0, 1, 2, 3, 4])

In [19]:
x[5:]

array([5, 6, 7, 8, 9])

In [20]:
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [27]:
X[0,:]

array([0, 1, 2, 3, 4])

In [28]:
X[0,:].ndim

1

In [29]:
X[:,0]

array([ 0,  5, 10])

In [30]:
X[:,0].ndim

1

In [31]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [33]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [34]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [38]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

 ### Reshape

In [39]:
x.shape

(10,)

In [40]:
x.ndim

1

In [41]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
b = x.reshape(1,10)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
b.ndim

2

In [47]:
x.ndim

1

In [48]:
b.shape

(1, 10)

In [49]:
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [50]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 合并操作

In [51]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [52]:
x

array([1, 2, 3])

In [53]:
y

array([3, 2, 1])

In [54]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [55]:
z = np.array([6,66,666])

In [56]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1,   6,  66, 666])

In [59]:
A = np.array([[1,2,3],
             [4,5,6]])

In [61]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([A,A] ,axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [63]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [64]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [65]:
A2 = np.concatenate([A,z.reshape(1,-1)])

In [66]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [67]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [68]:
B = np.full((2,2),100)

In [69]:
B

array([[100, 100],
       [100, 100]])

In [70]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [71]:
np.hstack([A,z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [72]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x1,x2,x3 = np.split(x,[3,7])

In [74]:
x1

array([0, 1, 2])

In [75]:
x2

array([3, 4, 5, 6])

In [76]:
x3

array([7, 8, 9])

In [77]:
x1,x2 = np.split(x,[5])

In [78]:
x1

array([0, 1, 2, 3, 4])

In [79]:
x2

array([5, 6, 7, 8, 9])

In [80]:
A = np.arange(16).reshape((4,4))

In [81]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
A1,A2 = np.split(A,[2])

In [83]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [84]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
A1, A2 = np.split(A, [2], axis = 1)

In [86]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [87]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [89]:
upper, lower = np.vsplit(A,[2])

In [90]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [91]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
left, right = np.hsplit(A,[2])

In [93]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [94]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [95]:
data=  np.arange(16).reshape((4,4))
X, y = np.hsplit(data,[-1])

In [96]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [97]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [98]:
y[:,0]

array([ 3,  7, 11, 15])