# 聚合操作

In [2]:
import numpy as np

L = np.random.random(100)

In [3]:
L

array([  9.04958136e-01,   7.79262968e-01,   6.11542032e-01,
         6.25133687e-01,   8.44486757e-01,   4.87027272e-01,
         4.92313786e-01,   5.56301785e-01,   9.32063294e-01,
         2.22735664e-01,   6.79728837e-01,   9.61125645e-03,
         5.55098604e-01,   4.88567748e-01,   8.82557877e-01,
         6.21541098e-01,   1.13560577e-01,   3.65826357e-01,
         1.25371532e-01,   8.82264360e-01,   2.02937644e-01,
         7.20932856e-01,   6.58236512e-01,   4.36421790e-01,
         2.34396319e-01,   4.42672669e-01,   3.60388659e-01,
         7.11705965e-02,   9.88097737e-01,   6.55531062e-01,
         1.63845137e-01,   8.17105430e-01,   8.67980353e-01,
         8.43747990e-01,   8.33597979e-02,   9.67018953e-02,
         6.48982401e-01,   3.93999727e-01,   7.62717718e-01,
         5.21453255e-01,   8.59989649e-01,   9.40716709e-01,
         4.10869557e-01,   7.62827982e-03,   5.70009504e-01,
         8.32976168e-02,   9.83450929e-01,   9.84943701e-01,
         5.05628601e-01,

In [4]:
sum(L)

52.275206959088834

In [5]:
np.sum(L)

52.275206959088827

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

73.8 ms ± 383 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
369 µs ± 9.42 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_array)

1.3796345510463937e-08

In [8]:
np.max(big_array)

0.99999980702063918

In [9]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

In [11]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [12]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [13]:
np.prod(X)

0

In [14]:
np.prod(X + 1)

20922789888000

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)

7.5

In [17]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2000000000000002

In [18]:
np.median(v)

2.0

In [19]:
np.percentile(big_array, q=50)

0.49969918627673166

In [20]:
np.median(big_array)

0.49969918627673166

In [21]:
np.percentile(big_array, q = 100)

0.99999980702063918

In [22]:
np.max(big_array)

0.99999980702063918

In [23]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

1.37963455105e-08
0.250181711623
0.499699186277
0.749428979534
0.999999807021


In [24]:
np.var(big_array)

0.083267704743196225

In [25]:
np.std(big_array)

0.28856144015303953

In [26]:
X = np.random.normal(0,1,size=1000000)

In [27]:
np.mean(X)

0.00011631005752704015

In [28]:
np.std(X)

1.000606875478693

## 索引

In [30]:
np.min(X)

-4.613214510779744

In [31]:
np.argmin(X)

71749

In [32]:
X[71749]

-4.613214510779744

In [33]:
np.argmax(X)

848572

In [34]:
X[848572]

4.6623450066283674

In [36]:
np.max(X)

4.6623450066283674

### 排序和使用索引

In [37]:
x = np.arange(16)

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
np.random.shuffle(x)
x

array([ 3, 13,  1, 14,  5, 15, 12,  0,  7,  2, 10,  8,  4,  9,  6, 11])

In [40]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
x

array([ 3, 13,  1, 14,  5, 15, 12,  0,  7,  2, 10,  8,  4,  9,  6, 11])

In [42]:
x.sort()

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
X = np.random.randint(10, size = (4,4))

In [47]:
X

array([[3, 0, 0, 9],
       [3, 3, 3, 8],
       [9, 7, 4, 3],
       [3, 8, 4, 6]])

In [48]:
np.sort(X)

array([[0, 0, 3, 9],
       [3, 3, 3, 8],
       [3, 4, 7, 9],
       [3, 4, 6, 8]])

In [49]:
np.sort(X, axis=1)

array([[0, 0, 3, 9],
       [3, 3, 3, 8],
       [3, 4, 7, 9],
       [3, 4, 6, 8]])

In [50]:
np.sort(X, axis=0)

array([[3, 0, 0, 3],
       [3, 3, 3, 6],
       [3, 7, 4, 8],
       [9, 8, 4, 9]])

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
np.random.shuffle(x)

In [53]:
x

array([ 8,  4,  6, 15,  9, 10, 14,  3,  1,  7,  5,  2, 11, 13, 12,  0])

In [54]:
np.argsort(x)

array([15,  8, 11,  7,  1, 10,  2,  9,  0,  4,  5, 12, 14, 13,  6,  3])

In [55]:
np.partition(x,3)

array([ 1,  0,  2,  3,  9, 10, 14,  4, 15,  7,  5,  6, 11, 13, 12,  8])

In [56]:
np.argpartition(x,3)

array([ 8, 15, 11,  7,  4,  5,  6,  1,  3,  9, 10,  2, 12, 13, 14,  0])

In [57]:
X

array([[3, 0, 0, 9],
       [3, 3, 3, 8],
       [9, 7, 4, 3],
       [3, 8, 4, 6]])

In [58]:
np.argsort(X,axis=1)

array([[1, 2, 0, 3],
       [0, 1, 2, 3],
       [3, 2, 1, 0],
       [0, 2, 3, 1]])

In [59]:
np.argsort(X,axis=0)

array([[0, 0, 0, 2],
       [1, 1, 1, 3],
       [3, 2, 2, 1],
       [2, 3, 3, 0]])

In [60]:
np.argpartition(X,2,axis=1)

array([[1, 2, 0, 3],
       [0, 1, 2, 3],
       [3, 2, 1, 0],
       [0, 2, 3, 1]])