In [18]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533, 2.331327],
              [3.110073, 1.781539],
              [1.343808, 3.368360],
              [3.582294, 4.679178],
              [2.280364, 2.866990],
              [7.423436, 4.696522],
              [5.745051, 3.533989],
              [9.172468, 2.511101],
              [7.792783, 3.424088],
              [7.939820, 0.791637]]
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607, 3.3657315])

In [19]:
%run kNN.py

In [20]:
predict_y = kNN_classify(6,X_train, y_train,x)

In [21]:
predict_y

1

## 使用scikit-learn中的kNN

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [24]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [25]:
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[ 8.093607   3.3657315].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
X_predict = x.reshape(1,-1)

In [27]:
X_predict

array([[ 8.093607 ,  3.3657315]])

In [28]:
kNN_classifier.predict(X_predict)

array([1])

In [29]:
y_predict = kNN_classifier.predict(X_predict)
y_predict[0]

1

### 重新整理kNN的代码

In [30]:
%run kNN_new.py

In [31]:
knn_clf = KNNClassifier(k=6)

In [33]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [34]:
y_predict = knn_clf.predict(X_predict)

In [35]:
y_predict

array([1])

In [36]:
y_predict[0]

1