## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 56,   7,  22,  39, 121, 106, 118,  42,  66,  49, 128, 112, 134,
        21, 125,   0,  43,  96,  48,  32,   8, 126,  82, 113,  23,  83,
        15, 101,  76,  61,  88, 108,  62,  89,  55, 138,  65,  94,  92,
       143,  40, 123, 115,  60,  59,   2,  44,   4, 131,   1,  79, 147,
        75, 122,  91, 100,  45, 111, 124, 107,  81, 135,  86,  41,   6,
        24,  25,  72,  37, 127, 105, 144,  17,  19,  14, 132,  71,  27,
        46, 116, 102,  13,  64,  10, 145,  97,  70,  16,  28, 104,  38,
       110, 114,  51,  36, 120,  67, 130,   9,  80,   5,  87,  29,  68,
        93,  26,  99,  11, 103,   3, 109,  52,  84,  18, 133, 119, 140,
       137,  57,  95,  77,  85,  31,  73,  53, 117,  69, 136,  90, 139,
        34, 146,  30, 141,  63,  74,  58,  98, 148,  33,  50,  78, 129,
        54,  12,  20, 142, 149,  47,  35])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([1, 2, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2,
       1, 1, 1, 0, 1, 1, 0, 2])

In [19]:
y_test

array([1, 2, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2,
       1, 2, 1, 0, 1, 1, 0, 2])

In [20]:
sum(y_predict == y_test)

28

In [21]:
sum(y_predict == y_test) / len(y_test)

0.9333333333333333

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
